// MEN'S PRODUCTS - 24 items
export const menProducts = [
  {
    id: "white-formal-shirt",
    name: "White Formal Shirt",
    price: 1299,
    originalPrice: 1799,
    image: "/images/men/1.jpg",
    images: ["/images/men/1.jpg", "/images/men/1A.jpg"],
    category: "Men",
    type: "FORMAL",
    description: "Classic white formal shirt crafted from premium cotton blend. Perfect for office wear, interviews, and formal occasions. Features a regular fit with full-length sleeves and button-down collar.",
    features: [
      "Premium 100% cotton fabric",
      "Regular fit for comfort",
      "Full-length buttoned sleeves",
      "Machine washable",
      "Wrinkle-resistant finish",
      "Button-down collar"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"]
  },
  {
    id: "navy-blue-cotton-shirt",
    name: "Navy Blue Cotton Shirt",
    price: 1499,
    originalPrice: 1999,
    image: "/images/men/2.jpg",
    images: ["/images/men/2.jpg", "/images/men/2A.jpg"],
    category: "Men",
    type: "FORMAL",
    description: "Sophisticated navy blue formal shirt in pure cotton. Ideal for professional settings and smart-casual events.",
    features: [
      "Pure cotton fabric",
      "Slim fit design",
      "Easy-iron technology",
      "Spread collar",
      "Single-button cuffs"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy Blue"]
  },
  {
    id: "grey-oxford-shirt",
    name: "Grey Oxford Shirt",
    price: 1199,
    originalPrice: 1599,
    image: "/images/men/3.jpg",
    images: ["/images/men/3.jpg", "/images/men/3A.jpg"],
    category: "Men",
    type: "FORMAL",
    description: "Timeless grey oxford shirt with a refined texture. Versatile piece for both business and casual occasions.",
    features: [
      "Oxford weave cotton",
      "Regular fit",
      "Button-down collar",
      "Breathable fabric",
      "Durable construction"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey"]
  },
  {
    id: "checkered-casual-shirt",
    name: "Checkered Casual Shirt",
    price: 1350,
    originalPrice: 1750,
    image: "/images/men/4.jpg",
    images: ["/images/men/4.jpg", "/images/men/4A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Trendy checkered shirt perfect for weekend outings and casual Fridays. Features a modern pattern and comfortable fit.",
    features: [
      "Cotton-poly blend",
      "Relaxed fit",
      "Checkered pattern",
      "Soft fabric",
      "Easy care"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red Check", "Blue Check"]
  },
  {
    id: "black-oversized-tee",
    name: "Black Oversized Tee",
    price: 799,
    originalPrice: 1199,
    image: "/images/men/5.jpg",
    images: ["/images/men/5.jpg", "/images/men/5A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Trendy oversized black t-shirt for a relaxed streetwear look. Made from soft cotton for all-day comfort.",
    features: [
      "100% cotton",
      "Oversized fit",
      "Crew neck",
      "Soft hand feel",
      "Perfect for layering"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"]
  },
  {
    id: "graphic-rock-tee",
    name: "Graphic Rock Tee",
    price: 699,
    originalPrice: 999,
    image: "/images/men/6.jpg",
    images: ["/images/men/6.jpg", "/images/men/6A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Express yourself with this bold graphic rock tee. Features vintage-inspired print on premium cotton.",
    features: [
      "Graphic print design",
      "Cotton blend",
      "Regular fit",
      "Ribbed crew neck",
      "Machine washable"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White"]
  },
  {
    id: "mustard-basic-tee",
    name: "Mustard Basic Tee",
    price: 599,
    originalPrice: 899,
    image: "/images/men/7.jpg",
    images: ["/images/men/7.jpg", "/images/men/7A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Essential mustard yellow t-shirt that adds a pop of color to your wardrobe. Perfect for casual days.",
    features: [
      "Soft cotton fabric",
      "Regular fit",
      "Solid color",
      "Crew neck",
      "Versatile styling"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Mustard Yellow"]
  },
  {
    id: "pure-white-crewneck",
    name: "Pure White Crewneck",
    price: 499,
    originalPrice: 699,
    image: "/images/men/8.jpg",
    images: ["/images/men/8.jpg", "/images/men/8A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Wardrobe staple white crewneck t-shirt. Classic design that pairs with everything.",
    features: [
      "Pure cotton",
      "Classic crewneck",
      "Regular fit",
      "Soft texture",
      "Everyday essential"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White"]
  },
  {
    id: "slim-fit-denim",
    name: "Slim Fit Denim",
    price: 2499,
    originalPrice: 3299,
    image: "/images/men/9.jpg",
    images: ["/images/men/9.jpg", "/images/men/9A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Modern slim fit denim jeans with stretch comfort. Classic blue wash perfect for any occasion.",
    features: [
      "Stretch denim",
      "Slim fit",
      "Five-pocket design",
      "Belt loops",
      "Medium wash"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Grey"]
  },
  {
    id: "beige-chino-pants",
    name: "Beige Chino Pants",
    price: 1899,
    originalPrice: 2499,
    image: "/images/men/10.jpg",
    images: ["/images/men/10.jpg", "/images/men/10A.jpg"],
    category: "Men",
    type: "FORMAL",
    description: "Versatile beige chino pants suitable for business casual and smart-casual settings.",
    features: [
      "Cotton twill fabric",
      "Regular fit",
      "Flat front",
      "Side pockets",
      "Wrinkle-resistant"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Beige", "Khaki", "Navy"]
  },
  {
    id: "black-cargo-joggers",
    name: "Black Cargo Joggers",
    price: 2199,
    originalPrice: 2799,
    image: "/images/men/11.jpg",
    images: ["/images/men/11.jpg", "/images/men/11A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Stylish black cargo joggers with multiple pockets. Perfect blend of comfort and utility.",
    features: [
      "Cargo pockets",
      "Elastic waistband",
      "Tapered fit",
      "Cotton blend",
      "Drawstring closure"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Olive", "Grey"]
  },
  {
    id: "black-summer-sandos",
    name: "Black Summer Sandos",
    price: 999,
    originalPrice: 1299,
    image: "/images/men/12.jpg",
    images: ["/images/men/12.jpg", "/images/men/12A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Comfortable black tank top for summer days and gym sessions. Lightweight and breathable.",
    features: [
      "Sleeveless design",
      "Lightweight fabric",
      "Athletic fit",
      "Moisture-wicking",
      "Breathable"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey"]
  },
  {
    id: "leather-biker-jacket",
    name: "Leather Biker Jacket",
    price: 4999,
    originalPrice: 6999,
    image: "/images/men/13.jpg",
    images: ["/images/men/13.jpg", "/images/men/13A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Premium leather biker jacket with asymmetrical zipper. Make a bold statement with this classic piece.",
    features: [
      "Genuine leather",
      "Asymmetric zipper",
      "Zippered pockets",
      "Quilted shoulders",
      "Inner lining"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Brown"]
  },
  {
    id: "urban-bomber-jacket",
    name: "Urban Bomber Jacket",
    price: 3499,
    originalPrice: 4499,
    image: "/images/men/14.jpg",
    images: ["/images/men/14.jpg", "/images/men/14A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Modern bomber jacket with ribbed cuffs and hem. Perfect for transitional weather.",
    features: [
      "Water-resistant",
      "Ribbed cuffs",
      "Front zipper",
      "Side pockets",
      "Polyester shell"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Olive"]
  },
  {
    id: "navy-woolen-coat",
    name: "Navy Woolen Coat",
    price: 6500,
    originalPrice: 8500,
    image: "/images/men/15.jpg",
    images: ["/images/men/15.jpg", "/images/men/15A.jpg"],
    category: "Men",
    type: "FORMAL",
    description: "Elegant navy blue woolen coat for winter. Sophisticated design with tailored fit.",
    features: [
      "Wool blend",
      "Tailored fit",
      "Notch lapel",
      "Button closure",
      "Inner pockets"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy"]
  },
  {
    id: "denim-trucker-jacket",
    name: "Denim Trucker Jacket",
    price: 2899,
    originalPrice: 3599,
    image: "/images/men/16.jpg",
    images: ["/images/men/16.jpg", "/images/men/16A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Classic denim trucker jacket with vintage wash. Timeless style that never goes out of fashion.",
    features: [
      "Denim fabric",
      "Button-front",
      "Chest pockets",
      "Adjustable cuffs",
      "Classic fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black", "Grey"]
  },
  {
    id: "grey-pullover-hoodie",
    name: "Grey Pullover Hoodie",
    price: 1999,
    originalPrice: 2599,
    image: "/images/men/17.jpg",
    images: ["/images/men/17.jpg", "/images/men/17A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Cozy grey hoodie with kangaroo pocket. Essential for casual comfort and streetwear style.",
    features: [
      "Fleece lining",
      "Kangaroo pocket",
      "Drawstring hood",
      "Ribbed cuffs",
      "Relaxed fit"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Navy"]
  },
  {
    id: "knitted-black-sweater",
    name: "Knitted Black Sweater",
    price: 1599,
    originalPrice: 2099,
    image: "/images/men/18.jpg",
    images: ["/images/men/18.jpg", "/images/men/18A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Warm knitted black sweater for cold days. Classic crewneck design with ribbed detailing.",
    features: [
      "Knit construction",
      "Crewneck",
      "Ribbed trim",
      "Soft wool blend",
      "Regular fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy"]
  },
  {
    id: "tie-dye-hoodie",
    name: "Tie-Dye Hoodie",
    price: 2299,
    originalPrice: 2999,
    image: "/images/men/19.jpg",
    images: ["/images/men/19.jpg", "/images/men/19A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Trendy tie-dye hoodie with unique color pattern. Stand out with this eye-catching piece.",
    features: [
      "Tie-dye pattern",
      "Pullover style",
      "Hood with drawstring",
      "Front pocket",
      "Cotton blend"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue Tie-Dye", "Pink Tie-Dye", "Purple Tie-Dye"]
  },
  {
    id: "vintage-sweatshirt",
    name: "Vintage Sweatshirt",
    price: 1799,
    originalPrice: 2299,
    image: "/images/men/20.jpg",
    images: ["/images/men/20.jpg", "/images/men/20A.jpg"],
    category: "Men",
    type: "CASUAL",
    description: "Retro-inspired vintage sweatshirt with distressed graphics. Comfortable and stylish.",
    features: [
      "Vintage design",
      "Crew neck",
      "Fleece interior",
      "Ribbed cuffs",
      "Relaxed fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Maroon"]
  },
  {
    id: "cotton-kurta-white",
    name: "Cotton Kurta (White)",
    price: 1499,
    originalPrice: 1999,
    image: "/images/men/21.jpg",
    images: ["/images/men/21.jpg", "/images/men/21A.jpg"],
    category: "Men",
    type: "ETHNIC",
    description: "Traditional white cotton kurta perfect for festive occasions and ethnic wear.",
    features: [
      "Pure cotton",
      "Mandarin collar",
      "Button placket",
      "Side slits",
      "Comfortable fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Off-White"]
  },
  {
    id: "black-pathani",
    name: "Black Pathani",
    price: 2499,
    originalPrice: 3299,
    image: "/images/men/22.jpg",
    images: ["/images/men/22.jpg", "/images/men/22A.jpg"],
    category: "Men",
    type: "ETHNIC",
    description: "Elegant black Pathani suit for special occasions. Classic ethnic wear with modern styling.",
    features: [
      "Premium fabric",
      "Traditional design",
      "Button closure",
      "Comfortable fit",
      "Ethnic wear"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"]
  },
  {
    id: "modi-jacket-grey",
    name: "Modi Jacket (Grey)",
    price: 2299,
    originalPrice: 2899,
    image: "/images/men/23.jpg",
    images: ["/images/men/23.jpg", "/images/men/23A.jpg"],
    category: "Men",
    type: "ETHNIC",
    description: "Sophisticated grey Modi jacket with Nehru collar. Perfect for formal and semi-formal events.",
    features: [
      "Nehru collar",
      "Button-front",
      "Side pockets",
      "Tailored fit",
      "Premium finish"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey"]
  },
  {
    id: "gym-training-tee",
    name: "Gym Training Tee",
    price: 899,
    originalPrice: 1199,
    image: "/images/men/24.jpg",
    images: ["/images/men/24.jpg", "/images/men/24A.jpg"],
    category: "Men",
    type: "ACTIVEWEAR",
    description: "Performance training t-shirt designed for intense workouts. Moisture-wicking and breathable.",
    features: [
      "Moisture-wicking",
      "Quick-dry fabric",
      "Athletic fit",
      "Breathable mesh",
      "Reflective details"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy"]
  }
];

// WOMEN'S PRODUCTS - 24 items
export const womenProducts = [
  {
    id: "midnight-bloom-anarkali",
    name: "Midnight Bloom Anarkali",
    price: 3499,
    originalPrice: 4499,
    image: "/images/women/1.jpg",
    images: ["/images/women/1.jpg", "/images/women/1A.jpg"],
    category: "Women",
    type: "ETHNIC",
    description: "Elegant midnight blue anarkali with intricate floral embroidery. Perfect for festive occasions and family gatherings. Crafted from premium georgette fabric for a graceful silhouette.",
    features: [
      "Premium georgette fabric",
      "Intricate leaf and floral embroidery",
      "Flared anarkali silhouette",
      "Matching dupatta included",
      "Dry clean only"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Midnight Blue"]
  },
  {
    id: "golden-zari-silk-saree",
    name: "Golden Zari Silk Saree",
    price: 5999,
    originalPrice: 7999,
    image: "/images/women/2.jpg",
    images: ["/images/women/2.jpg", "/images/women/2A.jpg"],
    category: "Women",
    type: "TRADITIONAL",
    description: "Luxurious silk saree with rich golden zari border and intricate pallu designs. A timeless piece of Indian heritage for weddings and special celebrations.",
    features: [
      "Pure silk blend fabric",
      "Artisanal golden zari border",
      "Rich woven pallu",
      "Contrast blouse piece included",
      "Grand ethnic look"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["FREE"],
    colors: ["Gold", "Red", "Green"]
  },
  {
    id: "ivory-chikankari-kurta",
    name: "Ivory Chikankari Kurta",
    price: 1899,
    originalPrice: 2499,
    image: "/images/women/3.jpg",
    images: ["/images/women/3.jpg", "/images/women/3A.jpg"],
    category: "Women",
    type: "ETHNIC",
    description: "Classic ivory white kurta featuring delicate hand-crafted Chikankari embroidery from Lucknow. Light, breathable, and perfect for summer days.",
    features: [
      "Breathable cotton voile",
      "Authentic Lucknowi Chikankari",
      "Side slits for comfort",
      "Elegant V-neckline",
      "Hand washable"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory"]
  },
  {
    id: "ruby-red-velvet-lehenga",
    name: "Ruby Red Velvet Lehenga",
    price: 12499,
    originalPrice: 15999,
    image: "/images/women/4.jpg",
    images: ["/images/women/4.jpg", "/images/women/4A.jpg"],
    category: "Women",
    type: "BRIDAL",
    description: "Stunning ruby red lehenga in heavy velvet fabric with premium stonework. Designed to make you stand out at any wedding event.",
    features: [
      "Heavy velvet fabric",
      "Premium stone and thread work",
      "Full volume ghera",
      "Customizable blouse",
      "Includes sheer dupatta"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ruby Red"]
  },
  {
    id: "emerald-green-sharara-set",
    name: "Emerald Green Sharara Set",
    price: 4299,
    originalPrice: 5499,
    image: "/images/women/5.jpg",
    images: ["/images/women/5.jpg", "/images/women/5A.jpg"],
    category: "Women",
    type: "FESTIVE",
    description: "Vibrant emerald green sharara set with a short kurta and flared pants. A modern twist on traditional ethnic wear.",
    features: [
      "Soft rayon crepe fabric",
      "Mirror work detailing",
      "Tiered sharara pants",
      "Modern ethnic silhouette",
      "Comfortable fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald Green"]
  },
  {
    id: "pastel-peach-organza-suit",
    name: "Pastel Peach Organza Suit",
    price: 3899,
    originalPrice: 4999,
    image: "/images/women/6.jpg",
    images: ["/images/women/6.jpg", "/images/women/6A.jpg"],
    category: "Women",
    type: "ETHNIC",
    description: "Delicate pastel peach suit set made from premium organza silk. Featuring a subtle shimmer and elegant floral prints.",
    features: [
      "Premium organza silk",
      "Subtle shimmer finish",
      "Floral block prints",
      "Lightweight and airy",
      "Semi-formal ethnic look"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pastel Peach"]
  },
  {
    id: "satin-champagne-slip-dress",
    name: "Satin Champagne Slip Dress",
    price: 2199,
    originalPrice: 2899,
    image: "/images/women/7.jpg",
    images: ["/images/women/7.jpg", "/images/women/7A.jpg"],
    category: "Women",
    type: "WESTERN",
    description: "Sleek champagne-colored slip dress in liquid satin. Features adjustable spaghetti straps and a flattering cowl neck.",
    features: [
      "Liquid satin finish",
      "Cowl neckline",
      "Adjustable spaghetti straps",
      "Side slit detail",
      "Perfect for cocktail parties"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Black", "Navy"]
  },
  {
    id: "black-lace-cocktail-dress",
    name: "Black Lace Cocktail Dress",
    price: 2899,
    originalPrice: 3599,
    image: "/images/women/8.jpg",
    images: ["/images/women/8.jpg", "/images/women/8A.jpg"],
    category: "Women",
    type: "PARTY",
    description: "Sophisticated black midi dress with intricate lace overlay. Designed with a fitted waist and elegant scalloped hemlines.",
    features: [
      "Intricate floral lace",
      "Midi length silhouette",
      "Lined for comfort",
      "Concealed back zipper",
      "Classic timeless black"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"]
  },
  {
    id: "floral-chiffon-maxi-dress",
    name: "Floral Chiffon Maxi Dress",
    price: 1999,
    originalPrice: 2599,
    image: "/images/women/9.jpg",
    images: ["/images/women/9.jpg", "/images/women/9A.jpg"],
    category: "Women",
    type: "CASUAL",
    description: "Flowy floral maxi dress in lightweight chiffon. Features a smocked waist and tiered skirt for a bohemian flair.",
    features: [
      "Lightweight chiffon fabric",
      "Smocked elastic waist",
      "Tiered skirt design",
      "Beautiful boho floral print",
      "Lined bodice"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Multi Floral"]
  },
  {
    id: "victorian-ruffle-white-blouse",
    name: "Victorian Ruffle White Blouse",
    price: 1299,
    originalPrice: 1699,
    image: "/images/women/10.jpg",
    images: ["/images/women/10.jpg", "/images/women/10A.jpg"],
    category: "Women",
    type: "TOPS",
    description: "Elegant white blouse inspired by Victorian fashion. Features delicate ruffle detailing on the neck and cuffs.",
    features: [
      "100% fine cotton",
      "Ruffle high neck",
      "Puff sleeves with ruffles",
      "Front button closure",
      "Semi-sheer fabric"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White"]
  },
  {
    id: "boho-chic-printed-skirt",
    name: "Boho-Chic Printed Skirt",
    price: 1450,
    originalPrice: 1899,
    image: "/images/women/11.jpg",
    images: ["/images/women/11.jpg", "/images/women/11A.jpg"],
    category: "Women",
    type: "BOTTOMS",
    description: "Vibrant boho-chic midi skirt with an ethnic block print. Features a comfortable drawstring waist and tassel details.",
    features: [
      "Soft cotton rayon blend",
      "Ethnic block print",
      "Elasticated drawstring waist",
      "Side pockets",
      "Flowy A-line cut"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Multi Print"]
  },
  {
    id: "crimson-wrap-party-dress",
    name: "Crimson Wrap Party Dress",
    price: 2599,
    originalPrice: 3299,
    image: "/images/women/12.jpg",
    images: ["/images/women/12.jpg", "/images/women/12A.jpg"],
    category: "Women",
    type: "PARTY",
    description: "Lustrous crimson red wrap dress that flatters every body type. Features a tie-up waist and flutter sleeves.",
    features: [
      "Silky soft fabric",
      "Versatile wrap design",
      "Flutter sleeves",
      "V-neckline",
      "Knee-length hem"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Crimson Red"]
  },
  {
    id: "tailored-charcoal-blazer",
    name: "Tailored Charcoal Blazer",
    price: 3299,
    originalPrice: 4299,
    image: "/images/women/13.jpg",
    images: ["/images/women/13.jpg", "/images/women/13A.jpg"],
    category: "Women",
    type: "OFFICE",
    description: "Sharp tailored blazer in charcoal grey. Perfect for board meetings and professional settings.",
    features: [
      "Structural shoulder pads",
      "Premium lining",
      "Sleek lapel design",
      "Double front pockets",
      "Crease-resistant fabric"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal Grey"]
  },
  {
    id: "high-waist-wide-leg-trousers",
    name: "High-Waist Wide Leg Trousers",
    price: 1799,
    originalPrice: 2399,
    image: "/images/women/14.jpg",
    images: ["/images/women/14.jpg", "/images/women/14A.jpg"],
    category: "Women",
    type: "OFFICE",
    description: "Sophisticated wide-leg trousers with a flattering high-waist design. Pairs perfectly with blouses and blazers.",
    features: [
      "Breathable poly-viscose",
      "High-waisted fit",
      "Wide leg silhouette",
      "Front pleat detail",
      "Zip and hook closure"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Black", "Navy", "Beige"]
  },
  {
    id: "dusty-rose-trench-coat",
    name: "Dusty Rose Trench Coat",
    price: 4999,
    originalPrice: 6499,
    image: "/images/women/15.jpg",
    images: ["/images/women/15.jpg", "/images/women/15A.jpg"],
    category: "Women",
    type: "WINTER",
    description: "Classic double-breasted trench coat in a beautiful dusty rose shade. A stylish outer layer for chilly days.",
    features: [
      "Water-resistant finish",
      "Classic belt tie",
      "Storm flap detailing",
      "Deep side pockets",
      "Lined for warmth"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dusty Rose", "Beige", "Navy"]
  },
  {
    id: "classic-indigo-skinny-jeans",
    name: "Classic Indigo Skinny Jeans",
    price: 1599,
    originalPrice: 2099,
    image: "/images/women/16.jpg",
    images: ["/images/women/16.jpg", "/images/women/16A.jpg"],
    category: "Women",
    type: "DENIM",
    description: "Ultimate skinny jeans in a deep indigo wash. Features high stretch for all-day comfort and shape retention.",
    features: [
      "High-stretch denim",
      "Slimming skinny fit",
      "Classic 5-pocket design",
      "Mid-rise waist",
      "Reinforced stitching"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Indigo", "Black", "Light Blue"]
  },
  {
    id: "oversized-cashmere-sweater",
    name: "Oversized Cashmere Sweater",
    price: 2499,
    originalPrice: 3299,
    image: "/images/women/17.jpg",
    images: ["/images/women/17.jpg", "/images/women/17A.jpg"],
    category: "Women",
    type: "WINTER",
    description: "Luxuriously soft oversized sweater crafted from a premium cashmere blend. The perfect cozy staple for your winter wardrobe.",
    features: [
      "Premium cashmere blend",
      "Cozy oversized fit",
      "Ribbed neck and cuffs",
      "Ultra-soft handfeel",
      "Warm yet lightweight"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Grey", "Beige", "Black"]
  },
  {
    id: "striped-cotton-summer-shirt",
    name: "Striped Cotton Summer Shirt",
    price: 999,
    originalPrice: 1299,
    image: "/images/women/18.jpg",
    images: ["/images/women/18.jpg", "/images/women/18A.jpg"],
    category: "Women",
    type: "CASUAL",
    description: "Lightweight blue and white striped shirt in 100% cotton. A versatile piece for casual outings or beach days.",
    features: [
      "100% breathable cotton",
      "Classic pinstripe pattern",
      "Relaxed fit",
      "Button-down front",
      "Curved hemline"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue/White Stripe"]
  },
  {
    id: "seamless-sculpt-yoga-set",
    name: "Seamless Sculpt Yoga Set",
    price: 2299,
    originalPrice: 2999,
    image: "/images/women/19.jpg",
    images: ["/images/women/19.jpg"],
    category: "Women",
    type: "ACTIVEWEAR",
    description: "High-performance seamless yoga set including a sports bra and high-waist leggings. Designed to sculpt and support.",
    features: [
      "4-way stretch fabric",
      "Moisture-wicking technology",
      "High-waist compression",
      "Seamless design",
      "Squat-proof fabric"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Grey", "Navy"]
  },
  {
    id: "lavender-fleece-hoodie",
    name: "Lavender Fleece Hoodie",
    price: 1499,
    originalPrice: 1999,
    image: "/images/women/20.jpg",
    images: ["/images/women/20.jpg", "/images/women/20A.jpg"],
    category: "Women",
    type: "CASUAL",
    description: "Ultra-soft lavender hoodie with a warm fleece lining. Featuring a front kangaroo pocket and adjustable drawstring hood.",
    features: [
      "Soft fleece lining",
      "Kangaroo front pocket",
      "Ribbed hem and cuffs",
      "Adjustable hood",
      "Relaxed lounge fit"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Lavender", "Grey", "Black"]
  },
  {
    id: "midnight-black-ribbed-leggings",
    name: "Midnight Black Ribbed Leggings",
    price: 899,
    originalPrice: 1199,
    image: "/images/women/21.jpg",
    images: ["/images/women/21.jpg"],
    category: "Women",
    type: "ACTIVEWEAR",
    description: "Stylish ribbed knit leggings in midnight black. Designed for both low-impact workouts and casual street style.",
    features: [
      "Breathable ribbed fabric",
      "High-waisted fit",
      "Wide elastic waistband",
      "Opaque squat-proof",
      "Comfortable stretch"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black"]
  },
  {
    id: "premium-silk-pajama-set",
    name: "Premium Silk Pajama Set",
    price: 1999,
    originalPrice: 2599,
    image: "/images/women/22.jpg",
    images: ["/images/women/22.jpg", "/images/women/22A.jpg"],
    category: "Women",
    type: "LOUNGEWEAR",
    description: "Luxurious silk-satin pajama set featuring a button-down top and elasticated trousers. Ultimate comfort for bedtime.",
    features: [
      "Silk-satin blend",
      "Button-up shirt with collar",
      "Piping detail",
      "Elasticated waist pants",
      "Luxe loungewear feel"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Champagne", "Black", "Navy"]
  },
  {
    id: "quilted-puffer-winter-jacket",
    name: "Quilted Puffer Winter Jacket",
    price: 3999,
    originalPrice: 4999,
    image: "/images/women/23.jpg",
    images: ["/images/women/23.jpg", "/images/women/23A.jpg"],
    category: "Women",
    type: "WINTER",
    description: "Insulated quilted puffer jacket designed for extreme cold. Features a detachable hood and water-repellent shell.",
    features: [
      "Thermal insulation",
      "Detachable faux-fur hood",
      "Weather-resistant shell",
      "Inner security pocket",
      "High collar design"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Olive"]
  },
  {
    id: "graphic-empower-cotton-tee",
    name: "Graphic 'Empower' Cotton Tee",
    price: 699,
    originalPrice: 999,
    image: "/images/women/24.jpg",
    images: ["/images/women/24.jpg", "/images/women/24A.jpg"],
    category: "Women",
    type: "CASUAL",
    description: "Premium cotton tee featuring a bold 'EMPOWER' graphic print. Soft, durable, and makes a powerful statement.",
    features: [
      "100% organic cotton",
      "High-quality screen print",
      "Relaxed crew neck",
      "Pre-shrunk fabric",
      "Durable stitching"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Grey"]
  }
];

// KIDS PRODUCTS - 24 items
export const kidsProducts = [
  {
    id: "classic-denim-dungarees",
    name: "Classic Denim Dungarees",
    price: 1299,
    originalPrice: 1699,
    image: "/images/kids/1.jpg",
    images: ["/images/kids/1.jpg", "/images/kids/1A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Classic denim dungarees for your little one. Durable, comfortable, and stylish for everyday adventures. Features adjustable straps and multiple pockets.",
    features: [
      "100% cotton denim",
      "Adjustable shoulder straps",
      "Front patch pocket",
      "Metal button closures",
      "Machine washable",
      "Comfortable fit"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Blue Denim", "Black Denim"]
  },
  {
    id: "urban-explorer-cargo-pants",
    name: "Urban Explorer Cargo Pants",
    price: 999,
    originalPrice: 1299,
    image: "/images/kids/2.jpg",
    images: ["/images/kids/2.jpg", "/images/kids/2A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Stylish cargo pants for little explorers. Multiple pockets and durable fabric perfect for active kids.",
    features: [
      "Cotton blend fabric",
      "Multiple cargo pockets",
      "Elastic waistband",
      "Adjustable drawstring",
      "Reinforced knees",
      "Casual wear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Olive", "Black", "Khaki"]
  },
  {
    id: "little-rockstar-biker-jacket",
    name: "Little Rockstar Biker Jacket",
    price: 2499,
    originalPrice: 3299,
    image: "/images/kids/3.jpg",
    images: ["/images/kids/3.jpg", "/images/kids/3A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Cool biker jacket for your little rockstar. Faux leather design with classic biker details.",
    features: [
      "Faux leather material",
      "Asymmetrical zipper",
      "Snap-down collar",
      "Zippered pockets",
      "Quilted details",
      "Party wear"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Black", "Brown"]
  },
  {
    id: "floral-meadow-cotton-dress",
    name: "Floral Meadow Cotton Dress",
    price: 1150,
    originalPrice: 1499,
    image: "/images/kids/4.jpg",
    images: ["/images/kids/4.jpg", "/images/kids/4A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Beautiful floral print cotton dress for your little princess. Lightweight and breathable for summer days.",
    features: [
      "Pure cotton fabric",
      "Floral print",
      "A-line silhouette",
      "Breathable material",
      "Knee-length",
      "Casual & party wear"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Pink Floral", "Blue Floral"]
  },
  {
    id: "dino-roar-graphic-tee",
    name: "Dino-Roar Graphic Tee",
    price: 599,
    originalPrice: 799,
    image: "/images/kids/5.jpg",
    images: ["/images/kids/5.jpg", "/images/kids/5A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Fun dinosaur graphic t-shirt that every little dino lover will adore. Soft cotton for all-day comfort.",
    features: [
      "100% cotton",
      "Dinosaur graphic print",
      "Crew neck",
      "Short sleeves",
      "Regular fit",
      "Machine washable"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Green", "Blue", "Red"]
  },
  {
    id: "superhero-caped-hoodie",
    name: "Superhero Caped Hoodie",
    price: 1499,
    originalPrice: 1999,
    image: "/images/kids/6.jpg",
    images: ["/images/kids/6.jpg", "/images/kids/6A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Superhero-themed hoodie with attached cape. Let your little hero save the day in style and comfort.",
    features: [
      "Fleece fabric",
      "Attached cape design",
      "Hood with drawstring",
      "Kangaroo pocket",
      "Ribbed cuffs",
      "Soft & warm"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Red", "Blue", "Black"]
  },
  {
    id: "velvet-party-tutu-skirt",
    name: "Velvet Party Tutu Skirt",
    price: 899,
    originalPrice: 1199,
    image: "/images/kids/7.jpg",
    images: ["/images/kids/7.jpg", "/images/kids/7A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Elegant velvet tutu skirt for special occasions. Perfect for parties, birthdays, and festive events.",
    features: [
      "Velvet fabric",
      "Tutu layers",
      "Elastic waistband",
      "Soft lining",
      "Party ready",
      "Available in multiple colors"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Burgundy", "Navy", "Black"]
  },
  {
    id: "safari-adventure-shorts",
    name: "Safari Adventure Shorts",
    price: 699,
    originalPrice: 899,
    image: "/images/kids/8.jpg",
    images: ["/images/kids/8.jpg", "/images/kids/8A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Durable safari-style shorts for outdoor adventures. Multiple pockets and comfortable fit.",
    features: [
      "Cotton twill fabric",
      "Multiple pockets",
      "Elastic waistband",
      "Comfortable fit",
      "Breathable",
      "Summer essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Khaki", "Olive", "Beige"]
  },
  {
    id: "polka-dot-sun-jumpsuit",
    name: "Polka Dot Sun Jumpsuit",
    price: 1399,
    originalPrice: 1799,
    image: "/images/kids/9.jpg",
    images: ["/images/kids/9.jpg", "/images/kids/9A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Adorable polka dot jumpsuit for sunny days. Lightweight and playful design for your little one.",
    features: [
      "Lightweight fabric",
      "Polka dot pattern",
      "Adjustable straps",
      "Button closures",
      "Breathable",
      "Summer style"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Red Polka", "Blue Polka"]
  },
  {
    id: "nautical-striped-polo",
    name: "Nautical Striped Polo",
    price: 850,
    originalPrice: 1099,
    image: "/images/kids/10.jpg",
    images: ["/images/kids/10.jpg", "/images/kids/10A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Classic nautical striped polo shirt. Perfect for both casual and semi-formal occasions.",
    features: [
      "Cotton pique fabric",
      "Navy and white stripes",
      "Ribbed collar",
      "Button placket",
      "Breathable",
      "Versatile style"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy/White", "Red/White"]
  },
  {
    id: "cozy-penguin-winter-pjs",
    name: "Cozy Penguin Winter PJs",
    price: 1100,
    originalPrice: 1499,
    image: "/images/kids/11.jpg",
    images: ["/images/kids/11.jpg", "/images/kids/11A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Warm and cozy penguin-themed pajamas for cold nights. Soft fleece keeps your child comfortable.",
    features: [
      "Fleece fabric",
      "Penguin print",
      "Long sleeves",
      "Full-length pants",
      "Elastic waistband",
      "Winter sleepwear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Blue", "Pink"]
  },
  {
    id: "galactic-space-sweatshirt",
    name: "Galactic Space Sweatshirt",
    price: 1250,
    originalPrice: 1599,
    image: "/images/kids/12.jpg",
    images: ["/images/kids/12.jpg", "/images/kids/12A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Out-of-this-world space-themed sweatshirt featuring planets and rockets. Soft and warm for cooler days.",
    features: [
      "Cotton-poly blend",
      "Space graphic print",
      "Crew neck",
      "Long sleeves",
      "Ribbed cuffs",
      "Machine washable"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy", "Black"]
  },
  {
    id: "rainbow-sparkle-leggings",
    name: "Rainbow Sparkle Leggings",
    price: 499,
    originalPrice: 699,
    image: "/images/kids/13.jpg",
    images: ["/images/kids/13.jpg", "/images/kids/13A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Fun rainbow sparkle leggings that add color to any outfit. Stretchy and comfortable for active play.",
    features: [
      "Stretchy fabric",
      "Rainbow design",
      "High waist",
      "Full-length",
      "Comfortable fit",
      "Mix & match"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Rainbow"]
  },
  {
    id: "tiny-gent-bowtie-suit",
    name: "Tiny Gent Bowtie Suit",
    price: 3299,
    originalPrice: 4299,
    image: "/images/kids/14.jpg",
    images: ["/images/kids/14.jpg", "/images/kids/14A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Sharp formal suit for your tiny gentleman. Perfect for weddings, parties, and special occasions.",
    features: [
      "Premium fabric blend",
      "Jacket with bowtie",
      "Formal pants",
      "Fully lined",
      "Special occasion",
      "Multiple sizes"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy", "Grey", "Black"]
  },
  {
    id: "mermaid-scale-swimsuit",
    name: "Mermaid Scale Swimsuit",
    price: 999,
    originalPrice: 1299,
    image: "/images/kids/15.jpg",
    images: ["/images/kids/15.jpg", "/images/kids/15A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Enchanting mermaid-scale swimsuit for pool and beach fun. UV-protective fabric keeps little mermaids safe.",
    features: [
      "Chlorine-resistant",
      "UV protection",
      "Mermaid scale design",
      "Quick-dry fabric",
      "Comfortable fit",
      "Swimwear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Teal", "Purple"]
  },
  {
    id: "camo-combat-joggers",
    name: "Camo Combat Joggers",
    price: 1199,
    originalPrice: 1499,
    image: "/images/kids/16.jpg",
    images: ["/images/kids/16.jpg", "/images/kids/16A.jpg"],
    category: "Kids",
    type: "BOYS WEAR",
    description: "Cool camo print joggers with combat-style pockets. Comfortable for play and stylish for casual outings.",
    features: [
      "Cotton blend",
      "Camo print",
      "Side pockets",
      "Elastic waistband",
      "Ribbed cuffs",
      "Casual wear"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Green Camo", "Grey Camo"]
  },
  {
    id: "sunshine-yellow-raincoat",
    name: "Sunshine Yellow Raincoat",
    price: 1899,
    originalPrice: 2399,
    image: "/images/kids/17.jpg",
    images: ["/images/kids/17.jpg", "/images/kids/17A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Bright yellow raincoat to keep your child dry on rainy days. Hooded design with fun animal ears.",
    features: [
      "Waterproof material",
      "Bright yellow color",
      "Hood with animal ears",
      "Snap closures",
      "Reflective details",
      "Rainy day essential"
    ],
    rating: 0,
    reviews: [],
    badge: "Limited",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Yellow"]
  },
  {
    id: "glitter-unicorn-sneakers",
    name: "Glitter Unicorn Sneakers",
    price: 1599,
    originalPrice: 1999,
    image: "/images/kids/18.jpg",
    images: ["/images/kids/18.jpg", "/images/kids/18A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Magical glitter unicorn sneakers that light up with every step. Comfortable and eye-catching footwear.",
    features: [
      "Glitter upper",
      "LED lights",
      "Non-slip sole",
      "Breathable lining",
      "Velcro straps",
      "Unicorn design"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["22", "23", "24", "25", "26", "27"],
    colors: ["Pink", "Purple"]
  },
  {
    id: "forest-friends-knit-sweater",
    name: "Forest Friends Knit Sweater",
    price: 1450,
    originalPrice: 1899,
    image: "/images/kids/19.jpg",
    images: ["/images/kids/19.jpg", "/images/kids/19A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Cozy knit sweater featuring adorable forest animal friends. Perfect for chilly days and family gatherings.",
    features: [
      "Acrylic wool blend",
      "Animal intarsia knit",
      "Crew neck",
      "Long sleeves",
      "Ribbed trim",
      "Winter warm"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Green", "Brown"]
  },
  {
    id: "active-mesh-sports-tee",
    name: "Active Mesh Sports Tee",
    price: 450,
    originalPrice: 599,
    image: "/images/kids/20.jpg",
    images: ["/images/kids/20.jpg", "/images/kids/20A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Breathable mesh sports t-shirt for active kids. Moisture-wicking fabric keeps them cool during play.",
    features: [
      "Moisture-wicking",
      "Mesh panels",
      "Breathable",
      "Quick-dry",
      "Athletic fit",
      "Sports & play"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Blue", "Red", "Green"]
  },
  {
    id: "pastel-dream-party-gown",
    name: "Pastel Dream Party Gown",
    price: 4500,
    originalPrice: 5999,
    image: "/images/kids/21.jpg",
    images: ["/images/kids/21.jpg", "/images/kids/21A.jpg"],
    category: "Kids",
    type: "GIRLS WEAR",
    description: "Dreamy pastel party gown for special celebrations. Layers of tulle and delicate details create a fairytale look.",
    features: [
      "Tulle layers",
      "Pastel colors",
      "Empire waist",
      "Full-length",
      "Soft lining",
      "Special occasion"
    ],
    rating: 0,
    reviews: [],
    badge: "Premium",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Lavender", "Mint", "Peach"]
  },
  {
    id: "plaid-weekend-flannel",
    name: "Plaid Weekend Flannel",
    price: 950,
    originalPrice: 1299,
    image: "/images/kids/22.jpg",
    images: ["/images/kids/22.jpg", "/images/kids/22A.jpg"],
    category: "Kids",
    type: "KIDS WEAR",
    description: "Classic plaid flannel shirt for weekend adventures. Soft and warm for casual family outings.",
    features: [
      "Soft flannel",
      "Plaid pattern",
      "Button front",
      "Chest pocket",
      "Long sleeves",
      "Casual wear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Red Plaid", "Blue Plaid"]
  },
  {
    id: "polka-dot-frill-socks-set",
    name: "Polka Dot Frill Socks Set",
    price: 350,
    originalPrice: 499,
    image: "/images/kids/23.jpg",
    images: ["/images/kids/23.jpg", "/images/kids/23A.jpg"],
    category: "Kids",
    type: "ACCESSORIES",
    description: "Adorable polka dot socks with frill trim. Set of 3 pairs to add charm to any outfit.",
    features: [
      "Cotton blend",
      "Polka dot pattern",
      "Frill trim",
      "Set of 3",
      "Comfortable fit",
      "Accessories"
    ],
    rating: 0,
    reviews: [],
    badge: "Best Seller",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["White/Polka", "Pink/Polka"]
  },
  {
    id: "kids-goggles",
    name: "Kids Goggles",
    price: 1050,
    originalPrice: 1399,
    image: "/images/kids/24.jpg",
    images: ["/images/kids/24.jpg", "/images/kids/24A.jpg"],
    category: "Kids",
    type: "ACCESSORIES",
    description: "Stylish protective goggles for your child. UV protection and comfortable fit for outdoor activities.",
    features: [
      "UV400 protection",
      "Impact-resistant",
      "Adjustable strap",
      "Comfortable fit",
      "Durable frame",
      "Outdoor essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["ONE SIZE"],
    colors: ["Blue", "Pink", "Black"]
  }
];

// NEW ARRIVALS - 24 items
export const newArrivalsProducts = [
  {
    id: "onyx-midnight-hoodie",
    name: "Onyx Midnight Hoodie",
    price: 4999,
    originalPrice: 6499,
    image: "/images/new-arrivals/1.jpg",
    images: ["/images/new-arrivals/1.jpg", "/images/new-arrivals/1A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Stay cozy and stylish with our signature heavyweight hoodie, crafted for the streets and beyond. Premium fleece lining for ultimate comfort. Features a modern fit and durable construction.",
    features: [
      "Premium heavyweight fleece",
      "Adjustable drawstring hood",
      "Kangaroo pocket",
      "Ribbed cuffs and hem",
      "Modern streetwear fit",
      "Machine washable"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy"]
  },
  {
    id: "titan-cargo-joggers",
    name: "Titan Cargo Joggers",
    price: 3499,
    originalPrice: 4499,
    image: "/images/new-arrivals/2.jpg",
    images: ["/images/new-arrivals/2.jpg", "/images/new-arrivals/2A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Utility meets style with these cargo joggers. Multiple pockets and tapered fit for a modern silhouette. Perfect for casual and outdoor wear.",
    features: [
      "Cotton-poly blend",
      "Multiple cargo pockets",
      "Tapered fit",
      "Elastic waistband",
      "Adjustable drawstring",
      "Casual comfort"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Olive", "Grey"]
  },
  {
    id: "phantom-bomber-jacket",
    name: "Phantom Bomber Jacket",
    price: 7999,
    originalPrice: 9999,
    image: "/images/new-arrivals/3.jpg",
    images: ["/images/new-arrivals/3.jpg", "/images/new-arrivals/3A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Bold, edgy, and built for the fearless. Our Phantom Bomber is the statement piece your wardrobe needs. Water-resistant and windproof with premium insulation.",
    features: [
      "Water-resistant shell",
      "Windproof construction",
      "Ribbed collar and cuffs",
      "Front zip closure",
      "Side pockets",
      "Premium insulation"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Olive"]
  },
  {
    id: "luna-satin-slip-dress",
    name: "Luna Satin Slip Dress",
    price: 5499,
    originalPrice: 6999,
    image: "/images/new-arrivals/4.jpg",
    images: ["/images/new-arrivals/4.jpg", "/images/new-arrivals/4A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Effortless elegance meets modern silhouette. The perfect piece for every occasion this season. Silky smooth fabric that drapes beautifully for a flattering look.",
    features: [
      "Luxury satin fabric",
      "Adjustable spaghetti straps",
      "Elegant drape",
      "Hidden side zipper",
      "Silky smooth finish",
      "Evening wear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Champagne", "Black", "Navy"]
  },
  {
    id: "aura-oversized-blazer",
    name: "Aura Oversized Blazer",
    price: 6999,
    originalPrice: 8999,
    image: "/images/new-arrivals/5.jpg",
    images: ["/images/new-arrivals/5.jpg", "/images/new-arrivals/5A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Make a statement with this oversized blazer. Structured shoulders and relaxed fit create a powerful silhouette for modern professionals.",
    features: [
      "Premium polyester blend",
      "Oversized fit",
      "Structured shoulders",
      "Notch lapel",
      "Two-button closure",
      "Office essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Beige"]
  },
  {
    id: "cargo-denim",
    name: "Cargo Denim",
    price: 2899,
    originalPrice: 3599,
    image: "/images/new-arrivals/6.jpg",
    images: ["/images/new-arrivals/6.jpg", "/images/new-arrivals/6A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Classic denim meets utility with cargo pockets. Durable construction and comfortable fit for everyday wear.",
    features: [
      "100% cotton denim",
      "Cargo pockets",
      "Regular fit",
      "Belt loops",
      "Five-pocket styling",
      "Durable construction"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Blue", "Black", "Grey"]
  },
  {
    id: "little-legend-tracksuit",
    name: "Little Legend Tracksuit",
    price: 1999,
    originalPrice: 2599,
    image: "/images/new-arrivals/7.jpg",
    images: ["/images/new-arrivals/7.jpg", "/images/new-arrivals/7A.jpg"],
    category: "New Arrivals",
    type: "KIDS WEAR",
    description: "Adventure-ready comfort for little trendsetters. Soft, durable, and cool for every playground moment. Perfect for active kids.",
    features: [
      "Soft cotton blend",
      "Full zip hoodie",
      "Elastic waist pants",
      "Ribbed cuffs",
      "Machine washable",
      "Active comfort"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy", "Grey", "Black"]
  },
  {
    id: "galaxy-print-hoodie",
    name: "Galaxy Print Hoodie",
    price: 2299,
    originalPrice: 2999,
    image: "/images/new-arrivals/8.jpg",
    images: ["/images/new-arrivals/8.jpg", "/images/new-arrivals/8A.jpg"],
    category: "New Arrivals",
    type: "KIDS WEAR",
    description: "Out-of-this-world galaxy print hoodie for young explorers. Soft and warm for cooler days.",
    features: [
      "Cotton-poly fleece",
      "Galaxy print",
      "Hood with drawstring",
      "Kangaroo pocket",
      "Ribbed cuffs",
      "Machine washable"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Navy", "Black", "Purple"]
  },
  {
    id: "star-dust-tulle-dress",
    name: "Star-Dust Tulle Dress",
    price: 3199,
    originalPrice: 3999,
    image: "/images/new-arrivals/9.jpg",
    images: ["/images/new-arrivals/9.jpg", "/images/new-arrivals/9A.jpg"],
    category: "New Arrivals",
    type: "GIRLS WEAR",
    description: "Magical tulle dress with star-dust sparkle. Perfect for parties and special occasions.",
    features: [
      "Tulle layers",
      "Sparkle details",
      "Soft lining",
      "Back zipper",
      "Party perfect",
      "Special occasion"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Pink", "Lavender", "Mint"]
  },
  {
    id: "graphite-flannel-shirt",
    name: "Graphite Flannel Shirt",
    price: 2599,
    originalPrice: 3299,
    image: "/images/new-arrivals/10.jpg",
    images: ["/images/new-arrivals/10.jpg", "/images/new-arrivals/10A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Classic flannel shirt in graphite plaid. Soft, warm, and perfect for layering.",
    features: [
      "Soft flannel fabric",
      "Graphite plaid pattern",
      "Button-front closure",
      "Chest pocket",
      "Long sleeves",
      "Casual style"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey Plaid", "Red Plaid", "Blue Plaid"]
  },
  {
    id: "nomad-ribbed-tee",
    name: "Nomad Ribbed Tee",
    price: 1299,
    originalPrice: 1699,
    image: "/images/new-arrivals/11.jpg",
    images: ["/images/new-arrivals/11.jpg", "/images/new-arrivals/11A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Essential ribbed t-shirt with comfortable stretch. Versatile piece for everyday styling.",
    features: [
      "Ribbed cotton",
      "Stretchy fabric",
      "Crew neck",
      "Short sleeves",
      "Body-hugging fit",
      "Everyday essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Grey", "Navy"]
  },
  {
    id: "obsidian-raw-denim",
    name: "Obsidian Raw Denim",
    price: 4299,
    originalPrice: 5499,
    image: "/images/new-arrivals/12.jpg",
    images: ["/images/new-arrivals/12.jpg", "/images/new-arrivals/12A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Premium raw denim jeans in obsidian black. Classic five-pocket style with modern fit.",
    features: [
      "Raw denim",
      "Slim fit",
      "Five-pocket styling",
      "Belt loops",
      "Button fly",
      "Premium quality"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Black", "Dark Blue"]
  },
  {
    id: "zenith-high-waist-flares",
    name: "Zenith High-Waist Flares",
    price: 3899,
    originalPrice: 4999,
    image: "/images/new-arrivals/13.jpg",
    images: ["/images/new-arrivals/13.jpg", "/images/new-arrivals/13A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Retro-inspired high-waist flare jeans. Flattering silhouette that elongates the legs.",
    features: [
      "Stretch denim",
      "High-waist",
      "Flare leg",
      "Five-pocket style",
      "Retro vibe",
      "Figure-flattering"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["24", "26", "28", "30", "32", "34"],
    colors: ["Blue", "Black"]
  },
  {
    id: "nova-cropped-puffer",
    name: "Nova Cropped Puffer",
    price: 8499,
    originalPrice: 10999,
    image: "/images/new-arrivals/14.jpg",
    images: ["/images/new-arrivals/14.jpg", "/images/new-arrivals/14A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Trendy cropped puffer jacket for winter. Lightweight yet warm with modern silhouette.",
    features: [
      "Puffer insulation",
      "Cropped length",
      "High collar",
      "Front zip",
      "Side pockets",
      "Winter essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Silver", "Navy"]
  },
  {
    id: "serene-knit-coord",
    name: "Serene Knit Co-ord",
    price: 5999,
    originalPrice: 7499,
    image: "/images/new-arrivals/15.jpg",
    images: ["/images/new-arrivals/15.jpg", "/images/new-arrivals/15A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Matching knit co-ord set for effortless style. Includes top and bottom for a complete look.",
    features: [
      "Knit fabric",
      "Matching set",
      "Comfortable fit",
      "Versatile styling",
      "Coordinated look",
      "Casual elegance"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Grey", "Black"]
  },
  {
    id: "mini-maven-denim-jacket",
    name: "Mini-Maven Denim Jacket",
    price: 2499,
    originalPrice: 3199,
    image: "/images/new-arrivals/16.jpg",
    images: ["/images/new-arrivals/16.jpg", "/images/new-arrivals/16A.jpg"],
    category: "New Arrivals",
    type: "KIDS WEAR",
    description: "Classic denim jacket for little ones. Durable and stylish for everyday adventures.",
    features: [
      "Cotton denim",
      "Button-front",
      "Chest pockets",
      "Adjustable cuffs",
      "Classic fit",
      "Kids style"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Blue", "Black"]
  },
  {
    id: "tots-rugged-overalls",
    name: "Tots' Rugged Overalls",
    price: 1799,
    originalPrice: 2399,
    image: "/images/new-arrivals/17.jpg",
    images: ["/images/new-arrivals/17.jpg", "/images/new-arrivals/17A.jpg"],
    category: "New Arrivals",
    type: "KIDS WEAR",
    description: "Durable overalls for active toddlers. Adjustable straps and multiple pockets.",
    features: [
      "Cotton denim",
      "Adjustable straps",
      "Multiple pockets",
      "Metal buckles",
      "Reinforced knees",
      "Toddler friendly"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Blue Denim", "Black Denim"]
  },
  {
    id: "hero-grade-raincoat",
    name: "Hero-Grade Raincoat",
    price: 2199,
    originalPrice: 2799,
    image: "/images/new-arrivals/18.jpg",
    images: ["/images/new-arrivals/18.jpg", "/images/new-arrivals/18A.jpg"],
    category: "New Arrivals",
    type: "KIDS WEAR",
    description: "Waterproof raincoat with superhero vibes. Keeps kids dry and stylish on rainy days.",
    features: [
      "Waterproof material",
      "Bright colors",
      "Hood with visor",
      "Snap closures",
      "Reflective details",
      "Rainy day fun"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    colors: ["Red", "Blue", "Yellow"]
  },
  {
    id: "pink-floral-dress",
    name: "Pink Floral Dress",
    price: 2499,
    originalPrice: 3299,
    image: "/images/new-arrivals/19.jpg",
    images: ["/images/new-arrivals/19.jpg", "/images/new-arrivals/19A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Beautiful pink floral dress perfect for spring and summer. Lightweight and flowy with a charming floral pattern all over. Ideal for casual outings, brunch dates, and garden parties.",
    features: [
      "Lightweight flowy fabric",
      "All-over floral print",
      "V-neckline",
      "Short sleeves",
      "Knee-length",
      "Perfect for casual wear"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink Floral"]
  },
  {
    id: "vogue-mesh-bodysuit",
    name: "Vogue Mesh Bodysuit",
    price: 1899,
    originalPrice: 2499,
    image: "/images/new-arrivals/20.jpg",
    images: ["/images/new-arrivals/20.jpg", "/images/new-arrivals/20A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Trendy mesh bodysuit with stylish details. Perfect for layering or wearing solo.",
    features: [
      "Mesh fabric",
      "Snap closure",
      "Stylish design",
      "Comfortable fit",
      "Layering piece",
      "Fashion forward"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Nude"]
  },
  {
    id: "black-sweater",
    name: "Black Sweater",
    price: 3599,
    originalPrice: 4599,
    image: "/images/new-arrivals/21.jpg",
    images: ["/images/new-arrivals/21.jpg", "/images/new-arrivals/21A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "A timeless wardrobe essential. Our premium knit Black Sweater delivers effortless style and all-day comfort. Made from the finest materials for lasting quality.",
    features: [
      "Premium knit fabric",
      "Classic crew neck",
      "Ribbed cuffs and hem",
      "Soft interior",
      "Versatile styling",
      "Warm and cozy"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"]
  },
  {
    id: "midnight-cargo-shorts",
    name: "Midnight Cargo Shorts",
    price: 2199,
    originalPrice: 2799,
    image: "/images/new-arrivals/22.jpg",
    images: ["/images/new-arrivals/22.jpg", "/images/new-arrivals/22A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Utility cargo shorts in midnight blue. Multiple pockets and comfortable fit for summer.",
    features: [
      "Cotton twill",
      "Cargo pockets",
      "Below knee length",
      "Elastic waist",
      "Drawstring closure",
      "Summer essential"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Black", "Khaki"]
  },
  {
    id: "summer-bloom-dress",
    name: "Summer Bloom Dress",
    price: 4599,
    originalPrice: 5899,
    image: "/images/new-arrivals/23.jpg",
    images: ["/images/new-arrivals/23.jpg", "/images/new-arrivals/23A.jpg"],
    category: "New Arrivals",
    type: "WOMENSWEAR",
    description: "Floral print dress that blooms with summer style. Lightweight and breezy for warm days.",
    features: [
      "Lightweight fabric",
      "Floral print",
      "V-neckline",
      "Short sleeves",
      "Knee-length",
      "Summer perfect"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Multi Floral"]
  },
  {
    id: "brown-leather-jacket",
    name: "Brown Leather Jacket",
    price: 4999,
    originalPrice: 6499,
    image: "/images/new-arrivals/24.jpg",
    images: ["/images/new-arrivals/24.jpg", "/images/new-arrivals/24A.jpg"],
    category: "New Arrivals",
    type: "MENSWEAR",
    description: "Premium brown leather jacket crafted from genuine leather. Classic biker style with a modern fit. Perfect for adding an edge to any outfit, whether casual or semi-formal.",
    features: [
      "Genuine leather material",
      "Classic biker style",
      "Asymmetrical front zipper",
      "Two side zippered pockets",
      "Soft inner lining",
      "Regular fit"
    ],
    rating: 0,
    reviews: [],
    badge: "New",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Brown", "Black"]
  }
];

// Combine all products
export const allProducts = [
  ...menProducts,
  ...womenProducts,
  ...kidsProducts,
  ...newArrivalsProducts
];